# Generated by Django 5.0.6 on 2024-07-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_likes_tweet_tweet_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='type',
            field=models.CharField(default='tweet', max_length=10),
        ),
    ]
