# Generated by Django 5.0.6 on 2024-07-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
