# Generated by Django 5.0.6 on 2024-07-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='tweet_liked',
            new_name='tweet',
        ),
    ]
