# Generated by Django 5.0.6 on 2024-07-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_rename_tweet_liked_likes_tweet'),
        ('tweets', '0002_remove_tweet_likes_tweet_tweet_created'),
        ('users', '0003_alter_user_joined_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
